import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ThemeRegistry from "./theme/ThemeRegistry";
import './global.css'


const geistRoboto = Roboto({
  variable: "--font-geist-roboto",
  subsets: ["latin"],
  weight: ['300', '400', '500'],
  style: ['normal',],
  display: 'swap',
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistRoboto.variable}`}>
        <ThemeRegistry>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
